### ISSUE TITLE
maybe support for Term::ANSIColor?

### ISSUE THREAD

**Issue by timo** [ryn1x/Terminal-Spinners#2]
By using inverted color you can get the "eights block" unicode characters to cycle through instead of throbbing back and forth. maybe that's worth considering.

**Comment by ryn1x** [comment]
That is an interesting idea. I will play around with it and add new spinners if it works.

**Comment by ryn1x** [comment]
I got this working, but using inverse leaves a small underline on the spinner and therefore there is a noticeable "jump" when going between normal and inverse portions of the animation. Since it does not look perfect and adds a dependency I am not sure I want to add this yet.

[An example of a bar3 using inverse](https://gist.github.com/ryn1x/32a1179ed02f8529abc8f41b58c00e7a)
